name: test_flame
description: Check flame useability
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.15.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.0.0-releasecandidate.16
  flame_forge2d: ^0.8.2-releasecandidate.15
  
flutter:
  assets:
    - assets/sample.json
